# Generated by Django 6.0.3 on 2026-03-14 18:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(limit_choices_to={'role': 'teacher'}, related_name='subjects', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватели'),
        ),
    ]
