# Generated by Django 6.0.3 on 2026-03-14 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('question_type', models.CharField(choices=[('single', 'Один правильный ответ'), ('multiple', 'Несколько правильных ответов')], default='single', max_length=10, verbose_name='Тип вопроса')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Изображение к вопросу')),
                ('code_snippet', models.TextField(blank=True, help_text='Код для вопроса (подсветка синтаксиса)', verbose_name='Фрагмент кода')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название теста')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('time_limit', models.PositiveIntegerField(default=60, help_text='Время в минутах на прохождение теста', verbose_name='Время на прохождение (минут)')),
                ('is_published', models.BooleanField(default=False, help_text='Если отмечено, тест доступен студентам', verbose_name='Опубликован')),
                ('show_correct_answers', models.BooleanField(default=True, help_text='Показывать ли правильные ответы после прохождения', verbose_name='Показывать правильные ответы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст ответа')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='answers/', verbose_name='Изображение к ответу')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
                'ordering': ['order'],
            },
        ),
    ]
