# Generated by Django 6.0.3 on 2026-04-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='shuffle_questions',
            field=models.BooleanField(default=False, help_text='Если отмечено, порядок вопросов и ответов будет случайным для каждого студента', verbose_name='Перемешивать вопросы'),
        ),
    ]
